# Generated by Django 4.2.4 on 2023-10-15 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedcycle',
            name='transaction',
        ),
        migrations.AddField(
            model_name='generatedcycle',
            name='dairy_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_cycles_dairy_name', to='dairy_management.dairy'),
        ),
        migrations.AddField(
            model_name='generatedcycle',
            name='dairy_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_cycles_dairy_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
