# Generated by Django 4.2.4 on 2023-10-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_management', '0002_remove_generatedcycle_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcycle',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedcycle',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
