# Generated by Django 4.2.4 on 2023-08-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('end_user_management', '0002_enduser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_code', models.CharField(blank=True, max_length=10, null=True)),
                ('center_code', models.CharField(max_length=10)),
                ('transaction_type', models.CharField(blank=True, choices=[('R', 'Receipt'), ('P', 'Payment')], max_length=1, null=True)),
                ('transaction_subtype', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('transaction_shift', models.CharField(blank=True, choices=[('M', 'Morning'), ('E', 'Evening')], max_length=1, null=True)),
                ('transaction_producer', models.CharField(max_length=10)),
                ('transaction_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_lacto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_snf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_water', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_protein', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_off_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_subtype_2', models.IntegerField(blank=True, null=True)),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_transactions', to='end_user_management.enduser')),
            ],
        ),
    ]
