# Generated by Django 4.2.4 on 2023-08-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_transaction_name', models.CharField(max_length=255)),
                ('success_records', models.PositiveIntegerField()),
                ('success_csv', models.FileField(upload_to='media/imported_csv/success/')),
                ('failed_records', models.PositiveIntegerField()),
                ('failed_csv', models.FileField(upload_to='media/imported_csv/failed/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='milktransaction',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='milktransaction',
            name='transaction_fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='milktransaction',
            name='transaction_liters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='milktransaction',
            name='transaction_shift',
            field=models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='milktransaction',
            name='transaction_snf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
