# Generated by Django 4.2.4 on 2023-08-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_transaction', '0002_importtransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtransaction',
            name='failed_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importtransaction',
            name='imported_transaction_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importtransaction',
            name='success_records',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
