# Generated by Django 4.2.4 on 2023-08-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_management', '0001_initial'),
        ('milk_transaction', '0003_alter_importtransaction_failed_records_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milktransaction',
            name='dairy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dairy_milk_transactions', to='dairy_management.dairy'),
        ),
    ]
