# Generated by Django 4.2.4 on 2023-08-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_transaction', '0005_importtransaction_dairy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milktransaction',
            name='center_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
