# Generated by Django 4.2.4 on 2023-08-12 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/dairy_logos/')),
                ('role', models.CharField(blank=True, max_length=255)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_established', models.DateField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_contact', models.CharField(blank=True, max_length=20)),
                ('milk_production_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('products', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('operational_status', models.BooleanField(default=True)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
