# Generated by Django 4.2.4 on 2024-02-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dairy',
            old_name='name',
            new_name='marathi_name',
        ),
        migrations.AddField(
            model_name='dairy',
            name='english_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
