# Generated by Django 4.2.4 on 2024-02-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_management', '0002_rename_name_dairy_marathi_name_dairy_english_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dairy',
            old_name='marathi_name',
            new_name='name',
        ),
    ]
