# Generated by Django 4.2.4 on 2023-10-18 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('end_user_management', '0002_enduser_password'),
        ('stock_food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_taken', models.PositiveBigIntegerField()),
                ('purchase_amount', models.PositiveBigIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_purchases_created_by', to=settings.AUTH_USER_MODEL)),
                ('dairy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_purchases_dairy', to='dairy_management.dairy')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_purchases_stock', to='stock_food.stock')),
                ('taken_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_purchases_user', to='end_user_management.enduser')),
            ],
        ),
    ]
