# Generated by Django 4.2.4 on 2023-10-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_food', '0002_feedpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpurchase',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedpurchase',
            name='total_purchase_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedpurchase',
            name='purchase_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedpurchase',
            name='quantity_taken',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
