# Generated by Django 4.2.4 on 2023-10-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_food', '0003_feedpurchase_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='marathit_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
