# Generated by Django 4.2.4 on 2023-10-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_food', '0004_stock_marathit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpurchase',
            name='purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feedpurchase',
            name='quantity_taken',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feedpurchase',
            name='total_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
