# Generated by Django 4.2.4 on 2023-11-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_food', '0005_alter_feedpurchase_purchase_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpurchase',
            name='extra_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
