# Generated by Django 4.2.4 on 2023-11-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_food', '0006_feedpurchase_extra_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpurchase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
