# Generated by Django 4.2.4 on 2023-08-13 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dairy_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.PositiveIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, max_length=254, null=True, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='media/profile_photos/')),
                ('user_status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dairy_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dairy_customers', to='dairy_management.dairy')),
                ('dairy_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
