# Generated by Django 4.2.4 on 2023-08-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='password',
            field=models.CharField(default='User@123'),
            preserve_default=False,
        ),
    ]
