# Generated by Django 4.2.4 on 2023-10-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_management', '0002_enduser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='marathi_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
