# Generated by Django 4.2.4 on 2023-12-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_management', '0003_enduser_marathi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enduser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='enduser',
            name='confirm_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enduser',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
