# Generated by Django 4.2.4 on 2023-12-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_management', '0005_alter_enduser_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='account_number',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='confirm_account_number',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
