# Generated by Django 4.2.4 on 2024-02-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_management', '0006_alter_enduser_account_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enduser',
            options={'ordering': ['custom_id']},
        ),
    ]
