# Generated by Django 4.2.4 on 2024-02-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_management', '0007_alter_enduser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='addhar_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='enduser',
            name='dist_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='enduser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='enduser',
            name='taluka_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='enduser',
            name='village_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
