# Generated by Django 4.2.4 on 2024-02-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_management', '0008_enduser_addhar_number_enduser_dist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='farmer_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
