# Generated by Django 4.2.4 on 2024-03-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_management', '0009_enduser_farmer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
