# Generated by Django 4.2.4 on 2023-09-03 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('end_user_management', '0002_enduser_password'),
        ('dairy_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_time', models.TimeField(default=django.utils.timezone.now)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('deduct', 'deduct'), ('withdrawal', 'Withdrawal')], max_length=20, null=True)),
                ('dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dairy_advance_payments', to='dairy_management.dairy')),
                ('enduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='end_user_management.enduser')),
            ],
        ),
    ]
