# Generated by Django 4.2.4 on 2023-09-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('deduct', 'Deduct'), ('withdrawal', 'Paid')], max_length=20, null=True),
        ),
    ]
