# Generated by Django 4.2.4 on 2023-10-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_payments', '0002_alter_advancepayment_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('deduct', 'Received'), ('withdrawal', 'Paid')], max_length=20, null=True),
        ),
    ]
