# Generated by Django 4.2.4 on 2023-10-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill_management', '0003_generatedcycle_from_date_generatedcycle_to_date'),
        ('advance_payments', '0003_alter_advancepayment_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='advance_taken_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles_with_advance', to='bill_management.generatedcycle'),
        ),
    ]
