# Generated by Django 4.2.4 on 2023-12-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_payments', '0004_advancepayment_advance_taken_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('deduct', 'Received'), ('withdrawal', 'Paid'), ('online_received', 'Online or Cash Received')], max_length=20, null=True),
        ),
    ]
