# Generated by Django 4.2.4 on 2023-09-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='transaction_source',
            field=models.CharField(blank=True, choices=[('import', 'Import Transaction'), ('create', 'Create Transaction')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('bonus_added', 'Bonus Added'), ('withdrawal', 'Withdrawal')], max_length=20, null=True),
        ),
    ]
