# Generated by Django 4.2.4 on 2023-09-03 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_app', '0002_bonus_transaction_source_bonus_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='bonus_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
