# Generated by Django 4.2.4 on 2023-12-12 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milk_transaction', '0006_alter_milktransaction_center_code'),
        ('bonus_app', '0003_bonus_bonus_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='milk_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_transactions', to='milk_transaction.milktransaction'),
        ),
    ]
